### PR TITLE
Update index2.html

### PR DESCRIPTION
**Pull request by jeanmicoste**
changes suggested by Bidouille

### CODE REVIEW

**Comment by marcus-aoo** [comment]
Thanks for the changes. I'll build a new website.

**Review by marcus-aoo — APPROVED** [review]

**Comment by Pilot-Pirx** [comment]
Hi Marcus,

why don't you simply merge the PR instead of committing manually?

Now we have another "dead" PR that must be closed...

Regards,

   Matthias

Am 27.09.22 um 18:28 schrieb marcus-aoo:

**Comment by marcus-aoo** [comment]
I've haven't seen any commit or merge funktion, button, ...
So, had to do it manually.

**Comment by Pilot-Pirx** [comment]
Are you member of The ASF? Then you should see the same as I do.

**Pull request closed without merging**
