### PR TITLE
Update index.html 

### PR DESCRIPTION
**Pull request by jeanmicoste**
changé Charset pour utf-8 pour caractères accentués

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
I think some other pages might require that as well.

**Review by Pilot-Pirx — COMMENTED** [review]
One "head" too much...

**Review by Pilot-Pirx — COMMENTED** [review]
One "head" too much.

**Comment by jeanmicoste** [comment]
Yes. Bad copy/paste...Jean-Michel CosteLe 11 avr. 2021 18:12, Matthias Seidel ***@***.***> a écrit :
@Pilot-Pirx commented on this pull request.

One "head" too much.

**Pull request merged**
