### PR TITLE
Correct typos in README

### PR DESCRIPTION
**Pull request by brnnnfx**
**What is this change?**

This change corrects spelling mistakes and capitalizes proper nouns and acronyms in `README.md`

**Why is this change necessary?**

This minor improvement will give readers a more polished reading experience.

### CODE REVIEW

**Comment by dave2wave** [comment]
Thank you for your contribution. Please fix the HTTPD and I'll accept this PR.

**Comment by brnnnfx** [comment]
Thanks for the review @dave2wave . Are you able merge this change in? I do not have sufficient access to do so.

**Comment by Pilot-Pirx** [comment]
Looks good to me!

@dave2wave Any objections to merge this?

**Comment by Pilot-Pirx** [comment]
Ping!

**Review by dave2wave — APPROVED** [review]

**Pull request merged**
